// Official and Verified Application Presets Database
// Note: Application requirements may vary by portal cycle. Always check official guidelines.

export const OFFICIAL_PRESETS = [
  {
    id: 'passport-in',
    name: 'Indian Passport Photo',
    description: 'Standard passport application photo specification (3.5 × 4.5 cm)',
    category: 'Government',
    targetWidth: 413,
    targetHeight: 531,
    minKb: 20,
    maxKb: 100,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '3.5:4.5',
    source: 'Passport Seva Portal Guidelines',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify official Passport Seva instructions.',
  },
  {
    id: 'us-visa',
    name: 'US Visa (DS-160 / Diversity Visa)',
    description: 'Square portrait with white background (2 × 2 inches / 600 × 600 px)',
    category: 'Government',
    targetWidth: 600,
    targetHeight: 600,
    minKb: 60,
    maxKb: 240,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '1:1',
    source: 'U.S. Dept of State Bureau of Consular Affairs',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify official travel.state.gov instructions.',
  },
  {
    id: 'upsc-photo',
    name: 'UPSC Civil Services Photo',
    description: 'Union Public Service Commission online application photo (350 × 350 px)',
    category: 'Government',
    targetWidth: 350,
    targetHeight: 350,
    minKb: 20,
    maxKb: 50,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '1:1',
    source: 'UPSC ORA Guidelines',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify official UPSC instructions.',
  },
  {
    id: 'ssc-photo',
    name: 'SSC CGL / CHSL Photo',
    description: 'Staff Selection Commission online application photo (100 × 120 px)',
    category: 'Government',
    targetWidth: 100,
    targetHeight: 120,
    minKb: 20,
    maxKb: 50,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '5:6',
    source: 'SSC Examination Notice',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify official SSC notice.',
  },
  {
    id: 'schengen-visa',
    name: 'Schengen Visa Photo',
    description: 'European Schengen Visa photograph (35 × 45 mm)',
    category: 'Government',
    targetWidth: 413,
    targetHeight: 531,
    minKb: 40,
    maxKb: 200,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '35:45',
    source: 'Schengen Consular Guidelines',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify consulate instructions.',
  },
  {
    id: 'gate-photo',
    name: 'GATE / IIT JEE Photo',
    description: 'National entrance examination photograph (480 × 640 px)',
    category: 'Education',
    targetWidth: 480,
    targetHeight: 640,
    minKb: 50,
    maxKb: 200,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '3:4',
    source: 'GOAPS Portal Guidelines',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify official GOAPS brochure.',
  },
  {
    id: 'neet-photo',
    name: 'NEET UG Photo',
    description: 'National Eligibility Entrance Test portrait with name and date plate',
    category: 'Education',
    targetWidth: 400,
    targetHeight: 600,
    minKb: 10,
    maxKb: 200,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '2:3',
    source: 'NTA NEET Information Bulletin',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify official NTA notice.',
  },
  {
    id: 'job-resume',
    name: 'Job Application Profile',
    description: 'Universal standard resume and job portal profile photo',
    category: 'Jobs',
    targetWidth: 400,
    targetHeight: 400,
    minKb: 20,
    maxKb: 150,
    format: 'PNG',
    formatLabel: 'PNG',
    aspectRatio: '1:1',
    source: 'Standard Recruiter Specifications',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary by employer portal.',
  },
  {
    id: 'college-admission',
    name: 'University Admission Document',
    description: 'College application portrait & identity photograph',
    category: 'Education',
    targetWidth: 300,
    targetHeight: 400,
    minKb: 20,
    maxKb: 100,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '3:4',
    source: 'University Admissions Portal Specs',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary by university portal.',
  },
  {
    id: 'scholarship-doc',
    name: 'National Scholarship Photo',
    description: 'NSP scholarship portal student portrait photo',
    category: 'Scholarships',
    targetWidth: 300,
    targetHeight: 300,
    minKb: 20,
    maxKb: 50,
    format: 'JPG',
    formatLabel: 'JPG',
    aspectRatio: '1:1',
    source: 'National Scholarship Portal (NSP)',
    sourceDate: '2026',
    isUserCreated: false,
    disclaimer: 'Requirements may vary. Verify NSP instructions.',
  },
];
